name: 'Michael Salgado | Poetry & Further'
favicon: null
layout_spectrum: 0.93516
typography_spectrum: 0.82748
title: 'Michael Salgado | Poetry & Further'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060407'
    - '#2f2f49'
    - '#c07687'
    - '#665f89'
    - '#ffa6a4'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
